using Saku_Overclock.Contracts.Services;
using Saku_Overclock.Core.Contracts;
using Saku_Overclock.Shared.Models;

namespace Saku_Overclock.Core.Services;

public class PremadePresetManagementService(
    IPresetManagerService presetManager, 
    IAppSettingsService appSettings, 
    IOcFinderService ocFinder) : IPremadePresetManagementService
{
    public void Initialize()
    {
        if (!appSettings.PremadePresetsAdded)
        {
            var ecoPreset = CreatePreset(PresetType.Balance);
            ecoPreset.PresetName = "Preset_SmartPreset";
            ecoPreset.PresetDesc = "Preset_SmartPresetDesc";
            ecoPreset.PresetIcon = "\uF4A5";
            ecoPreset.GeneratedType = AutoGeneratedType.Smart;

            var maximumPreset = CreatePreset(PresetType.Max);
            maximumPreset.PresetName = "Preset_PowerfulPreset";
            maximumPreset.PresetDesc = "Preset_PowerfulPresetDesc";
            maximumPreset.PresetIcon = "\uEC4A";
            ecoPreset.GeneratedType = AutoGeneratedType.Performance;
            
            presetManager.AddPresetInternal(ecoPreset);
            presetManager.AddPresetInternal(maximumPreset);
            presetManager.SaveSettings();
            
            appSettings.PremadePresetsAdded = true;
        }
    }

    private Preset CreatePreset(PresetType presetType)
    {
        var preset = ocFinder.CreatePreset(presetType, OptimizationLevel.Deep);
        return new Preset
        {
            CpuSettings = preset.SettingsOptions.CpuSettings,
            VrmSettings = preset.SettingsOptions.VrmSettings,
            CurveOptimizerOptions =  preset.SettingsOptions.CurveOptimizerOptions,
            CurveOptimizerAdvancedOptions = preset.SettingsOptions.CurveOptimizerAdvancedOptions,
            CpuModesSettings = preset.SettingsOptions.AdvancedCpuModesSettings
        };
    }
}